version: "3"

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network

  backend:
    build:
      context: ./zoologico-backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./zoologico-backend/.env
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    build:
      context: ./zoologico-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge